

server:
  port: 8001


spring:
  application:
    name: could-dept-provide-dept-8001
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/amber?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
# 显示后台处理的SQL语句
spring.jpa.show-sql: true
# 自动检查实体和数据库表是否一致，如果不一致则会进行更新数据库表
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.hbm2ddl.auto: update

spring.jpa.database: mysql